### PR TITLE
Properly handle disabled PCMs in RobotFactory

### LINKED ISSUE #117: Resolve all NullPointerException issues with disabled PCMs
- [x] Ghost all solenoids if PCM is disabled (`pcm` < 0). This covers a case where we may have a subsystem enabled for other hardware but we have no PCM.
- [x] Ghost the compressor if PCM is disabled.
- [x] ~Check for both PCM validity and `compressorEnabled` before enabling compressor. This prevents the mistake case where PCM is invalid but `compressorEnabled` = 1.~ (Not necessary with ghost compressor)

### PR DESCRIPTION
**Pull request by richiksc**
Fixes #117.

Urgent: merge before 2020-12-18.

@ddaymn Could you test this PR out on K-9?

### CODE REVIEW

File: src/main/java/com/team1816/lib/subsystems/Infrastructure.java [hunk 1]
```diff
@@ -23,7 +24,7 @@
     private Infrastructure() {
         super("Infrastructure");
         if (Constants.kPCMId >= 0) {
```
Comment (ddaymn) [inline src/main/java/com/team1816/lib/subsystems/Infrastructure.java:26]: You need to remove this if check for the constants it is bypassing the factory.  I would kust remove the entire constant at this point.

**Review by ddaymn — APPROVED** [review]
